### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ZagonAb** [mmatyas/pegasus-theme-flixnet#3]
Interesting theme for the pagasus frontend, I love how similar it is to a certain streaming platform. The only thing I don't understand and maybe it's because I'm NOT a programmer. It's because it uses screenshot and not video on the top right.
It's just a personal suggestion I make to you and I'd like to see if one day you decide to update the theme.
I think that only that small detail is missing to make it perfect! In the same way, I thank you for sharing your work with everyone!

**Comment by mmatyas** [comment]
Thanks! Back when I made this theme, I think that streaming platform showed only screenshots too, so that's what the theme followed. It is technically possible to show videos, though depending on the device, video playback might be a slow thing or involve installing codecs. An option to set which one to use would be probably the best.

**Comment by ZagonAb** [comment]
I answer myself!
I think it took me almost less than an hour to implement the video element inside the theme.qml and create the video.qml element with ChatGPT and it works perfectly!
https://youtu.be/aD_gmUbKbPk
what do you think?

**Comment by mmatyas** [comment]
Yup, looks nice!

**Comment by ZagonAb** [comment]
I think now I have confidence. I feel the theme is fabulous and now with a better video!
Sorry for the inconvenience and if someone wants the theme in .zip let me know to upload it or not!
Thank you.! good job.!!
